### ISSUE TITLE
Status and issues

### ISSUE THREAD

**Issue by gbraad** [weepee-org/openshift-asterisk#1]
@toonvd @ure I was curious about the status and/or issues with this project.

**Comment by toonvd** [comment]
Hi @gbraad,

The first commit version (with asterisk 13.11) is used in production for a while now.
It was used for a company with a lot of traffic. The 13.13 version has only been used in test, I had done the upgrade for webrtc compatibility and tested it by making phone calls with it for a few months. However, that project is not yet used in a production environment.

**Comment by gbraad** [comment]
@toonvd check. I started to test it. At the moment only as a deployment test for `minishift` to make sure we can handle different workloads. I had a small improvement at [gbraad/openshift-asterisk](/gbraad/openshift-asterisk/), but nothing substantial at this moment (speeds up by doing a shallow branch-based checkout).
